# Generated by Django 3.0.4 on 2021-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindmoi_bot', '0003_auto_20200113_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='stream',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reminder',
            name='topic',
            field=models.CharField(default='', max_length=30),
        ),
    ]
