# Generated by Django 3.2 on 2021-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remindmoi_bot', '0004_auto_20210416_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
